export * from './_app-context-data.model';
export * from './_configuration.model';
export * from './black-list.model';
export * from './budget.model';
export * from './fuel-types.model';
export * from './header-config.model';
export * from './icon-data.model';
export * from './insurance-company.model';
export * from './language.model';
export * from './literal.model';
export * from './location.model';
export * from './page-form.model';
export * from './quote-control.model';
export * from './quote-footer-comfig.model';
export * from './quote-settings.model';
export * from './quote-version.model';
export * from './signature.model';
export * from './stepper-config.model';
export * from './stepper.model';
export * from './quote-translate.model';

export type MaybePromise<T> = T | Promise<T>;
