import { RouteConfig } from '@shagui/ng-shagui/core';

export enum AppUrls {
  root = '**',
  pageNotFound = 'page-not-found',
  apology = 'apology-screen',
  onBoarding = 'on-boarding',
  isClient = 'is-client',
  isPolicyOwner = 'is-policy-owner',
  contactUs = 'contact-us',
  place = 'place',
  dateOfIssue = 'date-of-issue',
  licensePlate = 'license-plate',
  yourCarIs = 'your-car-is',
  drivingLicenseLocation = 'driving-license-location',
  drivingLicenseDate = 'driving-license-date',
  birthdate = 'birthdate',
  vehicle = 'vehicle',
  vehicleType = 'vehicle-type',
  confirmation = 'confirmation',
  offerings = 'offerings',
  make = 'make',
  numberAccidents = 'number-accidents',
  clientName = 'client-name',
  clientPhoneNumber = 'client-phone-number',
  clientEMail = 'client-email',
  clientIdentificationNumber = 'client-identification-number',
  insuranceCompanies = 'insurance-companies'
}

export const urls: RouteConfig = {
  [AppUrls.root]: { resetContext: false },
  [AppUrls.onBoarding]: { resetContext: false },
  [AppUrls.isClient]: { resetContext: false },
  [AppUrls.isPolicyOwner]: { resetContext: false },
  [AppUrls.contactUs]: { resetContext: false },
  [AppUrls.place]: { resetContext: false },
  [AppUrls.dateOfIssue]: { resetContext: false },
  [AppUrls.licensePlate]: { resetContext: false },
  [AppUrls.yourCarIs]: { resetContext: false },
  [AppUrls.birthdate]: { resetContext: false },
  [AppUrls.drivingLicenseLocation]: { resetContext: false },
  [AppUrls.drivingLicenseDate]: { resetContext: false },
  [AppUrls.vehicle]: { resetContext: false },
  [AppUrls.vehicleType]: { resetContext: false },
  [AppUrls.confirmation]: { resetContext: false },
  [AppUrls.offerings]: { resetContext: false },
  [AppUrls.make]: { resetContext: false },
  [AppUrls.numberAccidents]: { resetContext: false },
  [AppUrls.clientName]: { resetContext: false },
  [AppUrls.clientPhoneNumber]: { resetContext: false },
  [AppUrls.clientEMail]: { resetContext: false },
  [AppUrls.clientIdentificationNumber]: { resetContext: false },
  [AppUrls.insuranceCompanies]: { resetContext: false }
};
